spring.application.name=GymTracker

# Run this in MySQL Workbench or terminal before starting the app:
# CREATE DATABASE gym_tracker_db;
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect



server.port=8080
